[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
  "vela/=lib/vela/contracts/contracts/",
]
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fuzz]
runs = 1000
